//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseAPPM.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int ID { get; set; }
        public Nullable<bool> CustomersDel { get; set; }
        public Nullable<bool> EmployeesDel { get; set; }
        public Nullable<bool> SuppliersDel { get; set; }
        public Nullable<bool> SupplyRepresentativeDel { get; set; }
        public Nullable<bool> PrdouctsDel { get; set; }
        public Nullable<bool> StoreDel { get; set; }
        public Nullable<bool> BillDel { get; set; }
        public string U_Username { get; set; }
        public Nullable<bool> Main_Data { get; set; }
        public Nullable<bool> Managment { get; set; }
        public Nullable<bool> CustomersEdit { get; set; }
        public Nullable<bool> EmployeesEdit { get; set; }
        public Nullable<bool> SuppliersEdit { get; set; }
        public Nullable<bool> SupplyRepresentativeEdit { get; set; }
        public Nullable<bool> PrdouctsEdit { get; set; }
        public Nullable<bool> StoreEdit { get; set; }
        public Nullable<bool> BillEdit { get; set; }
        public Nullable<bool> Main_Data1 { get; set; }
        public Nullable<bool> Managment1 { get; set; }
        public Nullable<bool> Reports { get; set; }
    }
}
