//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseAPPM.Classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WarehouseEntities : DbContext
    {
        public WarehouseEntities()
            : base("name=WarehouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Administartion> Administartions { get; set; }
        public DbSet<JobsName> JobsNames { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TestLoop> TestLoops { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Warehouse_CategoryProduct> Warehouse_CategoryProduct { get; set; }
        public DbSet<Warehouse_Employee> Warehouse_Employee { get; set; }
        public DbSet<Warehouse_MainUnites> Warehouse_MainUnites { get; set; }
        public DbSet<Warehouse_Master_Store> Warehouse_Master_Store { get; set; }
        public DbSet<Warehouse_OutLayUnites> Warehouse_OutLayUnites { get; set; }
        public DbSet<Warehouse_Points> Warehouse_Points { get; set; }
        public DbSet<Warehouse_QT> Warehouse_QT { get; set; }
        public DbSet<Warehouse_Quantity_Product> Warehouse_Quantity_Product { get; set; }
        public DbSet<Warehouse_Qutaly> Warehouse_Qutaly { get; set; }
        public DbSet<Warehouse_Selling> Warehouse_Selling { get; set; }
        public DbSet<Warehouse_Selling_Master> Warehouse_Selling_Master { get; set; }
        public DbSet<Warehouse_Store> Warehouse_Store { get; set; }
        public DbSet<Warehouse_Suppliers> Warehouse_Suppliers { get; set; }
        public DbSet<Warehouse_SupplyRepresentative> Warehouse_SupplyRepresentative { get; set; }
        public DbSet<Warehouse_UnitesSub> Warehouse_UnitesSub { get; set; }
        public DbSet<Warehouse_Users> Warehouse_Users { get; set; }
        public DbSet<WarehouseCustomer> WarehouseCustomers { get; set; }
        public DbSet<Watehouse_BarCode> Watehouse_BarCode { get; set; }
        public DbSet<WatehouseProdouct> WatehouseProdoucts { get; set; }
    }
}
