//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseAPPM.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseCustomer
    {
        public WarehouseCustomer()
        {
            this.Warehouse_Selling_Master = new HashSet<Warehouse_Selling_Master>();
        }
    
        public int CustomersID { get; set; }
        public string CName { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> WDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> UsersID { get; set; }
    
        public virtual ICollection<Warehouse_Selling_Master> Warehouse_Selling_Master { get; set; }
    }
}
