//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseAPPM.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse_Selling
    {
        public int SellingId { get; set; }
        public int Selling_MasterID { get; set; }
        public Nullable<int> PointsId { get; set; }
        public Nullable<int> UnitesNId { get; set; }
        public Nullable<int> SUBUnitesId { get; set; }
        public string Notes { get; set; }
        public decimal TotalPrice { get; set; }
        public Nullable<int> Billno { get; set; }
        public Nullable<int> IdCategoryProduct { get; set; }
        public Nullable<int> ProdouctsId { get; set; }
        public Nullable<int> Quntity_Product { get; set; }
        public Nullable<int> UsersID { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<decimal> TotalBDiscount { get; set; }
        public Nullable<decimal> AMountDicount { get; set; }
        public Nullable<decimal> TotalAmountRow { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
    }
}
