//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseAPPM.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse_Users
    {
        public int UsersID { get; set; }
        public string U_Username { get; set; }
        public string U_Password { get; set; }
        public Nullable<System.DateTime> WDate { get; set; }
    }
}
