//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseAPPM.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse_Qutaly
    {
        public int QutalyID { get; set; }
        public Nullable<int> OutLayUnID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> UsersID { get; set; }
        public Nullable<System.DateTime> WDate { get; set; }
        public string Notes { get; set; }
        public string QName { get; set; }
    
        public virtual Warehouse_OutLayUnites Warehouse_OutLayUnites { get; set; }
    }
}
