//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseAPPM.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse_Store
    {
        public int StoreId { get; set; }
        public int SupplyRepId { get; set; }
        public int SuppliersId { get; set; }
        public Nullable<int> Billno { get; set; }
        public Nullable<decimal> PurchasingPrice { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
        public Nullable<int> IdCategoryProduct { get; set; }
        public Nullable<int> ProdouctsID { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<System.DateTime> Productiondate { get; set; }
        public Nullable<int> MinimumQT { get; set; }
        public Nullable<int> SizeProducts { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> Discount { get; set; }
        public int MStoreId { get; set; }
        public Nullable<decimal> TotalBDiscount { get; set; }
        public Nullable<decimal> AMountDicount { get; set; }
        public Nullable<decimal> TotalAmountRow { get; set; }
        public Nullable<int> UnitesNId { get; set; }
        public Nullable<int> SUBUnitesId { get; set; }
        public Nullable<decimal> TotalSize { get; set; }
        public Nullable<int> Quntity_Product { get; set; }
        public Nullable<int> QtStartPeriod { get; set; }
    }
}
