//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseAPPM.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse_MainUnites
    {
        public Warehouse_MainUnites()
        {
            this.Warehouse_UnitesSub = new HashSet<Warehouse_UnitesSub>();
        }
    
        public int UnitesNId { get; set; }
        public string UName { get; set; }
        public Nullable<System.DateTime> WDate { get; set; }
        public Nullable<int> UnitConvert { get; set; }
        public Nullable<int> UsersID { get; set; }
    
        public virtual ICollection<Warehouse_UnitesSub> Warehouse_UnitesSub { get; set; }
    }
}
