//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseAPPM.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse_OutLayUnites
    {
        public Warehouse_OutLayUnites()
        {
            this.Warehouse_Qutaly = new HashSet<Warehouse_Qutaly>();
        }
    
        public int OutLayUnID { get; set; }
        public string QName { get; set; }
        public Nullable<System.DateTime> WDate { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<Warehouse_Qutaly> Warehouse_Qutaly { get; set; }
    }
}
