//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseAPPM.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse_Points
    {
        public int Pointsid { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> TotalPoint { get; set; }
        public Nullable<System.DateTime> WDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> EmpId { get; set; }
    }
}
