//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseAPPM.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse_QT
    {
        public int ID { get; set; }
        public Nullable<int> STartQT { get; set; }
        public Nullable<int> IDStore { get; set; }
        public Nullable<int> CUTQT { get; set; }
    }
}
