//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseAPPM.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse_UnitesSub
    {
        public int UnitesId { get; set; }
        public Nullable<int> UnitesNId { get; set; }
        public Nullable<int> UnitConvert { get; set; }
        public string UnitsSubName { get; set; }
    
        public virtual Warehouse_MainUnites Warehouse_MainUnites { get; set; }
    }
}
