//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseAPPM.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Watehouse_BarCode
    {
        public int BarCodeID { get; set; }
        public Nullable<int> BarcodeCategory_Product { get; set; }
        public Nullable<int> BarCodeProduct { get; set; }
        public Nullable<System.DateTime> BarCodeDate { get; set; }
        public string BarCodeText { get; set; }
    }
}
