//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseAPPM.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class WatehouseProdouct
    {
        public int ProdouctsID { get; set; }
        public Nullable<int> IdCategoryProduct { get; set; }
        public string Pname { get; set; }
        public Nullable<System.DateTime> WDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> UsersID { get; set; }
        public Nullable<int> BarCodeText { get; set; }
    
        public virtual Warehouse_CategoryProduct Warehouse_CategoryProduct { get; set; }
    }
}
